services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
  # google-cloud-sdk:
  #   image: google/cloud-sdk:latest
  #   ports:
  #     - "8000:8000"

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redis
  #   env_file: ".env"